version: "4"

services:
  db:
    image: bitnami/postgresql:13.16.0
    restart: always
    container_name: br-db
    tty: true
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=br
    ports: 
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U use"]
      interval: 10s
      timeout: 5s
      retries: 5
